Probono-GCC/frontend

- src/Components/test.js
> Add Test.js to component

- src/Assets/test.js
- src/Auth/test.js
- src/Pages/test.js
- src/Styles/test.js
- src/Util/test.js
> Add 5 Test.js

- src/Components/AppBar.js
- src/index.js
Merge 후 소소한 Conflict 해결 
- 이슈: Home.js, Calender.module.css 가 소문자로 되어있어서 계속 오류가 나는데 깃허브에 파일 올릴 때 파일명은 어떻게 수정해야 하는지?
어떤 변경 사항이 있나요?
> "Fix Merge Conflict in index.js, AppBar.js"

- src/Pages/TeacherView.js
> Fix wrong path

- src/Components/AppBar.js
- src/Pages/ClassBoard.js
- src/Pages/CreateClass.js
- src/Pages/NoticeBoard.js
- src/Pages/Post.js
- src/Pages/TeacherView.js
- src/index.js
- Post.js: 게시글 클릭 시 보이는 화면
- CreateClass.js: Student View의 표를 응용하여 생성
- ClassBoard.js: NoticeBoard의 표를 응용하여 생성 
- `ClassBoard용 게시글 화면, 게시글 추가 화면의 경우 각 화면별 링크를 만들어야 하는건가?`
- `Classes 내 하위 반들의 경우 어떻게 해야할지는 아직 모르겠다.`
- AppBar 변경: 현재까지 추가된 모든 메뉴로 이동할 수 있도록 링크 연결 
어떤 변경 사항이 있나요?
> [Sprint 6-2] CreateClass, Classboard 추가, PostForm, AppBar 변경

- src/Components/Button.js
- src/Components/ForgotPassword.js
- src/Components/LoginContainer.js
- src/Pages/Login.js
- src/Styles/css/Button.module.css
- src/Styles/css/Login.module.css
모바일 버전 뷰 업데이트
- 로그인 뷰
- 패스워드 찾기 뷰
어떤 변경 사항이 있나요?
- [ x ] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.)
> [Sprint 7-2] 모바일 뷰 개선 작업 중 - 로그인 뷰 완료

- src/Components/AppBar.js
- src/Components/InfoBox.js
- src/Pages/AssignHomeroom.js
- src/Pages/ClassNewPostForm.js
- src/Pages/CreateClass.js
- src/Pages/MyProfile.js
- src/Pages/Post.js
- src/Pages/StudentView.js
- src/Pages/SubjectBoard.js
- src/Pages/SubjectInfo.js
- src/Pages/SubjectNewPostForm.js
- src/Pages/TeacherView.js
- src/index.js
- Subject Board용 js 파일 추가 (Class Board와 큰 차이 없음)
- Assign Homeroom 메뉴 추가 (아직 미완성)
어떤 변경 사항이 있나요?
> [Sprint 7-2] Subject Board, Assign Homeroom 추가

- src/Components/Table.js
- src/Pages/AssignHomeroom.js
- src/Pages/ClassInfo.js
- src/Pages/CreateClass.js
- src/Pages/StudentView.js
- src/Pages/SubjectInfo.js
- src/Pages/TeacherView.js
- src/Styles/css/Table.module.css
- AssignHomeroom 코드 완성
- 테이블 id 속성 추가 -> 디자인 개별 지정 가능
어떤 변경 사항이 있나요?
> [Sprint 7-2] Update AssignHomeroom.js, Table id added

- src/Components/AppBar.js
- src/Components/Button.js
- src/Pages/CommonCourseManagement.js
- src/Pages/ElectiveCourseManagement.js
- src/Styles/css/Button.module.css
- src/index.js
- Common Course Management 메뉴 추가
- 버튼 CSS 변경 -> 최대 길이 설정
어떤 변경 사항이 있나요?
> [Sprint 7-2] Add CommonCourseManagement, Update Button CSS

- src/Components/AppBar.js
- src/Components/ChangePasswordModal.js
- src/Components/LoginContainer.js
- src/Components/Table.js
- src/Pages/ChangePassword.js
- src/Pages/NoticeBoard.js
- src/Pages/NoticeNewPostForm.js
- src/Pages/Post.js
- src/Pages/StudentView.js
- src/index.css
- src/index.js
- src/store/MediaQueryContext.js
공지 게시판 모바일 뷰 레이아웃 조정
비밀번호 변경 페이지 추가
테이블 체크박스 옵션 수정
어떤 변경 사항이 있나요?
> [Sprint7-2] 모바일 뷰 레이아웃 조정, 비밀번호 변경 페이지 개발

- src/Components/CalendarEventModal.js
- src/Components/SelectButton.js
- src/Components/SelectButtonContatiner.js
- src/Pages/AssignHomeroom.js
- src/Pages/CommonCourseManagement.js
- src/Pages/ElectiveCourseManagement.js
- src/Styles/css/Modal.module.css
- Course Management 페이지 완성
- SelectButton, SelectButtonContainer 컴포넌트 추가
어떤 변경 사항이 있나요?
> [Sprint 7-2] Course Management 페이지 완성

- src/Components/ChangePasswordModal.js
- src/Components/Table.js
- src/Pages/ChangePassword.js
- src/Pages/StudentView.js
- src/Styles/css/Table.module.css
> [Sprint7-2] Student View 테이블 체크박스 수정

- src/Apis/Api/User.js
- src/Pages/CreateAccount.js
- src/Pages/StudentView.js
- Axios Connect First Try
어떤 변경 사항이 있나요?
> Axios Connect First Try

- src/Apis/Api/User.js
- src/Components/ChangeGradeModal.js
- src/Components/ChangePasswordModal.js
- src/Pages/ChangeGrade.js
- src/Pages/ChangePassword.js
- src/Pages/CreateAccount.js
- src/Pages/CreateClass.js
- src/Pages/NoticeNewPostForm.js
- src/Pages/TeacherView.js
- Student View, Teacher View, Change PW, grade의 API 추가 (get, post 연결)
- Backend Error 미해결: 
어떤 변경 사항이 있나요?
> Update API in Student View, Teacher View, Change PW, grade

- package-lock.json
- src/Apis/Api/User.js
- src/Components/ChangeGradeModal.js
- src/Components/ChangePasswordModal.js
- src/Pages/ChangeGrade.js
- src/Pages/ChangePassword.js
- src/Pages/CreateAccount.js
- src/Pages/StudentView.js
- src/Pages/TeacherView.js
- src/Route/PrivateRoutes.js
- CreateAccount: id, pw 등 입력값의 정규표현식 추가 후 체크하는 로직 추가
- Student, Teacher View에서 삭제하는 로직 추가
- Grade, PW 수정하는 로직 추가
- 마이페이지 완성 후 Grade, PW 수정하는 로직 최종 점검 가능! 현재는 "Birth, sex, Image and password answer are required for the first update." 에러가 뜨는 상태
어떤 변경 사항이 있나요?
> [Sprint 8-1] Update CreateAccount regex, check logic / Delete User logic / Changing grade, pw logics

- src/Apis/Api/Class.js
- src/Pages/AssignHomeroom.js
- src/Pages/ChangeGrade.js
- src/Pages/ChangePassword.js
- src/Pages/CreateAccount.js
- src/Pages/CreateClass.js
- src/Pages/StudentView.js
- src/Pages/TeacherView.js
- User API 변경에 따른 코드 수정: Student, Teacher 사용하는 부분 수정
- Class.js API 연결 완료 (테이블 handleRowSelection 부분이 문제 생김, 체크박스 2개 생기는 문제)
- AssignHomeroom.js API 일부 연결 완료 
- Class, Teacher, Student 명단 받아오는 것까지는 완료
- 그러나 Student 테이블 체크박스 및 handleRowSelection 부분 때문에 더이상 진행 막힘
어떤 변경 사항이 있나요?
> [Sprint 8-1] User API 연결 부분 수정, Class API 연결

- package-lock.json
- src/Apis/Api/Notice.js
- src/Apis/Api/User.js
- src/Apis/Utils/Axios.js
- src/Components/AppBar.js
- src/Components/LoginContainer.js
- src/Pages/MyProfile.js
- src/Pages/NoticeBoard.js
- src/Pages/NoticeNewPostForm.js
- src/Pages/Post.js
- src/Pages/PrivateRoute.js
- src/Route/PublicRoute.js
- src/Util/CheckFirstAccess.js
- src/store/AuthContext.js
프로필 - 첫번째 접속 유저 판별 후 post, put 테스트 완료
전체 notice - 리스트 불러오기, 작성하기, 삭제하기 테스트 완료
백엔드 오류 fix 후 진행할 사항 : notice 리스트 조회 시 image list 정보 누락, 리스트 정렬 재요청, 게시글 수정하기
어떤 변경 사항이 있나요?
>  [Sprint 8-1] 프로필 api 연동 완료, notice api 연동 작업 진행중

- src/Apis/Api/Class.js
- src/Apis/Api/Notice.js
- src/Apis/Api/User.js
- src/Components/AppBar.js
- src/Components/ChangeGradeModal.js
- src/Components/ChangePasswordModal.js
- src/Components/LoginContainer.js
- src/Components/Table.js
- src/Components/ViewTable.js
- src/Pages/AssignHomeroom.js
- src/Pages/ChangeGrade.js
- src/Pages/ChangePassword.js
- src/Pages/CreateAccount.js
- src/Pages/CreateClass.js
- src/Pages/MyProfile.js
- src/Pages/NoticeBoard.js
- src/Pages/NoticeNewPostForm.js
- src/Pages/Post.js
- src/Pages/StudentView.js
- src/Pages/TeacherView.js
- src/Styles/css/Table.module.css
- src/Util/CheckFirstAccess.js
- src/Util/checkFirstAccessTeacher.js
- src/index.js
admin classlist 동적 nav구성
어떤 변경 사항이 있나요?
> [Sprint8-2]

- src/Components/DetailTable.js
- src/Components/Modal.js
- src/Pages/NoticeNewPostForm.js
- src/Pages/StudentView.js
- src/Pages/TeacherView.js
> [Sprint8-2] student view, teacher view 상세보기 화면 완료, notice 수정하기 new api 연동 완료

- package-lock.json
- package.json
- src/Apis/Api/Class.js
- src/Apis/Api/Course.js
- src/Apis/Api/Subject.js
- src/Components/AppBar.js
- src/Pages/CommonCourseManagement.js
- src/Pages/CreateClass.js
Common Course Management API 연결 중
어떤 변경 사항이 있나요?
> [Sprint 8-2] Common Course Management API 연결 중

- src/Apis/Api/Class.js
- src/Apis/Api/ClassNotice.js
- src/Components/AppBar.js
- src/Pages/AssignHomeroom.js
- src/Pages/ClassBoard.js
- src/Pages/ClassNewPostForm.js
- src/Pages/NoticeBoard.js
- src/Route/PublicRoute.js
- src/index.js
> [Sprint8-2] Class board 생성

- src/Apis/Api/Class.js
- src/Apis/Api/ClassNotice.js
- src/Components/AppBar.js
- src/Components/Table.js
- src/Pages/AssignHomeroom.js
- src/Pages/ClassBoard.js
- src/Pages/ClassNewPostForm.js
- src/Pages/NoticeNewPostForm.js
- src/Pages/Post.js
- src/Route/PrivateRoutes.js
> [Sprint8-2] assign home room error fix, class board api연동, notice 게시판 error fix

- src/Pages/CreateAccount.js
> fix serialNumberChecked condition in handleRegister()

- src/Pages/CreateAccount.js
> Update grades in CreateAccount.js

- src/Apis/Api/Class.js
- src/Apis/Api/Course.js
- src/Components/AppBar.js
- src/Pages/AssignHomeroom.js
- src/Pages/ClassBoard.js
- src/Pages/ClassInfo.js
- src/Pages/ClassNewPostForm.js
- src/Pages/CommonCourseManagement.js
- src/Pages/CreateClass.js
- src/Pages/Post.js
> [Sprint 9-1] Class Board 사용성 개선, Assign home room 페이지네이션 수정

- src/Components/AppBar.js
> Update click Avartar event to go to Myprofile in AppBar.js

- src/Apis/Api/Course.js
- src/Pages/CommonCourseManagement.js
Update common course management teacher api 연동 완료
어떤 변경 사항이 있나요?
> [Sprint9-1] Common course management teacher페이지 완료

- src/Apis/Api/Course.js
- src/Components/AppBar.js
- src/Pages/CommonCourseManagement.js
> Course management 누락 api 연동 완료

- src/Components/AppBar.js
- src/Components/LoginContainer.js
- src/Pages/Login.js
- src/Pages/MyProfile.js
- src/Pages/NoticeBoard.js
- src/Route/PrivateRoutes.js
- src/Route/PublicRoute.js
> [Sprint9-1] 로그인 창 앞으로가기 화면 동작 제어

- src/Apis/Api/User.js
- src/Components/AppBar.js
- src/Components/Modal.js
- src/Pages/AssignHomeroom.js
- src/Pages/NoticeBoard.js
- src/Pages/NoticeNewPostForm.js
- src/Pages/Post.js
- src/Pages/TeacherView.js
- src/Route/PublicRoute.js
- src/Util/DateUtils.js
- src/index.js
3차 알파테스트 bug fix 중
어떤 변경 사항이 있나요?
> 3차 알파테스트 일부 bug fix

- src/Apis/Api/User.js
- src/Components/AppBar.js
- src/Pages/CreateAccount.js
> Fix user id 중복 체크 로직 수정

- src/Apis/Api/User.js
- src/Components/AppBar.js
- src/Components/DetailTable.js
- src/Components/Modal.js
- src/Components/NoticeStack.js
- src/Components/PaginationTable.js
- src/Pages/AssignHomeroom.js
- src/Pages/ChangeGrade.js
- src/Pages/ChangePassword.js
- src/Pages/CommonCourseManagement.js
- src/Pages/MyProfile.js
- src/Pages/NoticeBoard.js
- src/Pages/NoticeNewPostForm.js
- src/Pages/Post.js
- src/Pages/TeacherView.js
- src/Styles/css/Table.module.css
home room 선생님 정보 업데이트, 라디오 버튼 체크 기능 개선, 게시판 이미지 삭제 기능 추가
어떤 변경 사항이 있나요?
> [Sprint 9-1] 4차 알파테스트 fix

- src/Components/AppBar.js
- src/Pages/ClassBoard.js
- src/Pages/MyProfile.js
- src/Pages/Post.js
App bar UX개선, student profile info grade,section fetch
어떤 변경 사항이 있나요?
> [Sprint9-1]App bar UX개선, student profile info grade,section fetch

- src/Components/ForgotPassword.js
- src/Components/Modal.js
- src/Pages/AssignHomeroom.js
- src/Pages/ChangePassword.js
- src/Pages/ClassBoard.js
- src/Pages/ClassInfo.js
- src/Pages/ClassNewPostForm.js
- src/Pages/MyProfile.js
- src/Pages/NoticeNewPostForm.js
> Fix 알파테스트 ver4.3 오류 수정

- src/Pages/MyProfile.js
- src/Route/PrivateRoutes.js
- Fix profile image check logic
어떤 변경 사항이 있나요?
> [Sprint 9-2] Fix profile image check logic

- src/Components/NoticeStack.js
- src/Pages/MyProfile.js
- src/Route/PrivateRoutes.js
Fix noticeStack createdAt to updatedAt time
어떤 변경 사항이 있나요?
> [Sprint 9-2] Fix noticeStack createdAt to updatedAt time

- src/Components/NoticeStack.js
- src/Pages/ClassBoard.js
- src/Pages/MyProfile.js
- src/Pages/NoticeBoard.js
- src/Pages/Post.js
- src/Pages/StudentView.js
> [Sprint9-1]UI 수정 및 detail view 정보 추가

- src/Components/Button.js
- src/Pages/CommonCourseManagement.js
- src/Pages/CreateClass.js
- src/Styles/css/Button.module.css
Update button UI 개선 및 css 색깔 조정
어떤 변경 사항이 있나요?
> Update button UI 개선 및 css 색깔 조정

- src/Components/DetailTable.js
- src/Pages/Post.js
포스트 작성자 수정, null 값 표시 -으로 수정
어떤 변경 사항이 있나요?
> [Sprint 9-2] 포스트 작성자 수정, null 값 표시 -으로 수정

- src/Components/AppBar.js
- src/Components/InfoBox.js
- src/Components/NoticeStack.js
- src/Components/PaginationTable.js
- src/Components/Table.js
- src/Components/ViewTable.js
- src/Pages/ChangePassword.js
- src/Pages/ClassBoard.js
- src/Pages/ClassInfo.js
- src/Pages/CreateAccount.js
- src/Pages/NoticeBoard.js
- src/Pages/StudentView.js
- src/Pages/TeacherView.js
> [Sprin9-1] mobile 화면 UI 개선

- src/Components/LoginContainer.js
- src/Pages/CommonCourseManagement.js
- src/Pages/CreateAccount.js
- src/Pages/Login.js
Fix Teacher acoount create logic
(PW 달라도 가입되는 오류 수정)
어떤 변경 사항이 있나요?
> [Sprint 9-1] 교사 계정 생성 오류, 강좌 관리 뒤로가기 버튼 오류, 로그인 엔터 개선

- src/Components/AppBar.js
- src/Components/InfoBox.js
- src/Components/ViewTable.js
- src/Pages/ClassBoard.js
- src/Pages/ClassNewPostForm.js
- src/Pages/CommonCourseManagement.js
- src/Pages/NoticeBoard.js
- src/Pages/NoticeNewPostForm.js
- src/Pages/StudentView.js
- src/Pages/TeacherView.js
- src/Styles/css/Table.module.css
- src/index.css
모바일 UI 개선, app bar close 조정
어떤 변경 사항이 있나요?
> 모바일 UI 개선, app bar UX 개선

- src/Apis/Api/Class.js
- src/Pages/AssignHomeroom.js
- src/Pages/CreateClass.js
> api 수정사항 및 예외처리 재연결

- public/index.html
> Update title of site

- src/Pages/ClassNewPostForm.js
- src/Pages/NoticeNewPostForm.js
> 게시글 작성 링크 삽입 기능 추가

- src/Components/Calender.js
- src/Util/DateUtils.js
캘린더 add버튼 권한 설정
어떤 변경 사항이 있나요?
> 캘린더 add버튼 권한 설정

- src/Components/CalendarEventModal.js
- src/Styles/css/Modal.module.css
> Update 모달 추가 UI개선

- package-lock.json
- package.json
- src/Components/AppBar.js
- src/Components/Button.js
- src/Pages/ClassAttendanceReport.js
- src/Pages/TodayAttendance.js
- src/Route/PrivateRoutes.js
- src/Styles/css/Attendance.module.css
- src/index.css
> 일별 출석부, 월별 출석 통계 페이지 페이지 추가

- src/Components/AppBar.js
> Update attendance메뉴 임시 숨김

- src/Pages/Login.js
> fix const Lang by adding initialLang in Login.js

- src/Components/Button.js
- src/Components/ForgotPassword.js
- src/Components/LoginContainer.js
- src/Pages/ChangePassword.js
- src/Pages/StudentView.js
- src/Pages/SubjectInfo.js
- src/Styles/css/Login.module.css
> Update login view mobile css조정

- src/Apis/Api/User.js
- src/Components/AppBar.js
- src/Pages/StudentView.js
> Update grade별 student view

- src/Apis/Api/Translate.js
> Update postTranslateData() log in Translate.js

- src/Pages/AssignHomeroom.js
- src/Pages/ChangeGrade.js
- src/Pages/MyProfile.js
- src/Pages/StudentView.js
> Update 프로필 grade수정 기능 추가

- src/Components/LoginContainer.js
- src/Styles/css/Login.module.css
> Update login 화면 css수정

- src/Pages/MyProfile.js
- src/Pages/StudentView.js
> Update StudentView 셀렉트 박스 위치조정

- src/Apis/Api/Translate.js
- src/Components/ChangeGradeModal.js
- src/Components/ChangePasswordModal.js
- src/Components/ForgotPassword.js
- src/Components/Modal.js
- src/Components/NoticeStack.js
- src/Components/PaginationTable.js
- src/Pages/AssignHomeroom.js
- src/Pages/ChangeGrade.js
- src/Pages/ChangePassword.js
- src/Pages/MyProfile.js
- src/Pages/Post.js
- src/Util/TextToSpeech.js
- src/i18n/i18n.js
> 버튼UI 조정, view table row개수조정

- src/Components/PaginationTable.js
- src/Components/ViewTable.js
- src/Pages/ClassAttendanceReport.js
- src/Pages/ClassInfo.js
- src/Pages/CommonCourseManagement.js
- src/Pages/CreateClass.js
- src/Pages/StudentView.js
- src/Styles/css/Button.module.css
- src/Styles/css/Modal.module.css
student view export excel 기능 추가, table pagination숨김, 버튼 UI조정
어떤 변경 사항이 있나요?
> Update student view export excel 기능 추가,table pagination숨김, 버튼 UI조정

- src/Components/AppBar.js
- src/Components/LanguageSwitcher.js
- src/Components/NoticeStack.js
- src/Pages/AppPolicy.js
- src/Pages/Login.js
- src/Route/PublicRoute.js
- src/i18n/i18n.js
> Fix 번역 key수정

- src/Pages/StudentView.js
> Update StudentView.js 주석 수정

- .github/workflows/build-and-test.yml
- .github/workflows/deploy.yml
> env파일 명령어 수정

- .github/workflows/build-and-test.yml
- .github/workflows/deploy.yml
> env 파일 명령어 수정
